from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from bs4 import BeautifulSoup
from tqdm import tqdm
import time
import requests

# ✅ Add all users here — cookie only if available
user_cookie_strings = {
    "Keerthish": "speedoughSession=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJrc2QiLCJlbWFpbCI6ImtzZHdvcmsyMDI1QGdtYWlsLmNvbSIsImVtYWlsVmVyaWZpZWQiOm51bGwsImlzX2FjdGl2ZSI6dHJ1ZSwiaXNfc3VwZXJ1c2VyIjpmYWxzZSwiaW1hZ2UiOiJodHRwczovL3NwZWVkb3VnaC5ib3JpbmdhdmF0YXJzLmRldi9hcGkvYXZhdGFyP3ZhcmlhbnQ9YmVhbSZuYW1lPWtzZCZjb2xvcnM9RUZFQUU2LEVFQUYzQSwwMzBFMEYsRUY5RkJDZyw2NUMzQzgmc3F1YXJlIiwicm9sZSI6ImNyZWF0b3IiLCJjcmVhdG9yX2lkIjo1MTg4LCJjcmVhdGVkX2F0IjoiMjAyNS0wNi0xMlQwMTo1NjowMS40NzFaIiwidXBkYXRlZF9hdCI6IjIwMjUtMDYtMTJUMDE6NTY6MzAuNzMyWiIsImlkIjoiNTMzNyIsImZhdm9yaXRlX3JldGFpbGVycyI6W119LCJuYW1lIjoia3NkIiwiZW1haWwiOiJrc2R3b3JrMjAyNUBnbWFpbC5jb20iLCJwaWN0dXJlIjoiaHR0cHM6Ly9zcGVlZG91Z2guYm9yaW5nYXZhdGFycy5kZXYvYXBpL2F2YXRhcj92YXJpYW50PWJlYW0mbmFtZT1rc2QmY29sb3JzPUVGRUFFNixFRUFGM0EsMDMwRTBGLEVGOUZCQ2csNjVDM0M4JnNxdWFyZSIsInN1YiI6IjUzMzciLCJyb2xlIjoiY3JlYXRvciIsImlhdCI6MTc0OTcwNzczNn0.bmhdow3cspTgfM611tdvSeReDLy7H85Q12tzBq_jGa4",
    "Jibin": "speedoughSession=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJqc2QiLCJlbWFpbCI6ImpzZHdvcmsyMDI1QGdtYWlsLmNvbSIsImVtYWlsVmVyaWZpZWQiOm51bGwsImlzX2FjdGl2ZSI6dHJ1ZSwiaXNfc3VwZXJ1c2VyIjpmYWxzZSwiaW1hZ2UiOiJodHRwczovL3NwZWVkb3VnaC5ib3JpbmdhdmF0YXJzLmRldi9hcGkvYXZhdGFyP3ZhcmlhbnQ9YmVhbSZuYW1lPUphbWUmY29sb3JzPUVGRUFFNixFRUFGM0EsMDMwRTBGLEVGOUZCQ2csNjVDM0M4JnNxdWFyZSIsInJvbGUiOiJjcmVhdG9yIiwiY3JlYXRvcl9pZCI6NTE4NiwiY3JlYXRlZF9hdCI6IjIwMjUtMDYtMTJUMDE6NDM6MTcuNzEyWiIsInVwZGF0ZWRfYXQiOiIyMDI1LTA2LTEyVDAxOjQ1OjQxLjEzMVoiLCJpZCI6IjUzMzUiLCJmYXZvcml0ZV9yZXRhaWxlcnMiOltdfSwibmFtZSI6ImpzZCIsImVtYWlsIjoianNkd29yazIwMjVAZ21haWwuY29tIiwicGljdHVyZSI6Imh0dHBzOi8vc3BlZWRvdWdoLmJvcmluZ2F2YXRhcnMuZGV2L2FwaS9hdmF0YXI_dmFyaWFudD1iZWFtJm5hbWU9SmFtZSZjb2xvcnM9RUZFQUU2LEVFQUYzQSwwMzBFMEYsRUY5RkJDZyw2NUMzQzgmc3F1YXJlIiwic3ViIjoiNTMzNSIsInJvbGUiOiJjcmVhdG9yIiwiaWF0IjoxNzQ5NzA3NTYxfQ.POf1aOSbvSvgLL8kSa8846xNKnQ86KQ9hzfk2z94L58",
    "Vishnu": "speedoughSession=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJ2c2QiLCJlbWFpbCI6InZzZHdvcmsyMDI1QGdtYWlsLmNvbSIsImVtYWlsVmVyaWZpZWQiOm51bGwsImlzX2FjdGl2ZSI6dHJ1ZSwiaXNfc3VwZXJ1c2VyIjpmYWxzZSwiaW1hZ2UiOiJodHRwczovL3NwZWVkb3VnaC5ib3JpbmdhdmF0YXJzLmRldi9hcGkvYXZhdGFyP3ZhcmlhbnQ9YmVhbSZuYW1lPXZzZCZjb2xvcnM9RUZFQUU2LEVFQUYzQSwwMzBFMEYsRUY5RkJDZyw2NUMzQzgmc3F1YXJlIiwicm9sZSI6ImNyZWF0b3IiLCJjcmVhdG9yX2lkIjo1MTkwLCJjcmVhdGVkX2F0IjoiMjAyNS0wNi0xMlQwMjowMDozOS40NjNaIiwidXBkYXRlZF9hdCI6IjIwMjUtMDYtMTJUMDI6MDE6MzcuMjQ0WiIsImlkIjoiNTMzOSIsImZhdm9yaXRlX3JldGFpbGVycyI6W119LCJuYW1lIjoidnNkIiwiZW1haWwiOiJ2c2R3b3JrMjAyNUBnbWFpbC5jb20iLCJwaWN0dXJlIjoiaHR0cHM6Ly9zcGVlZG91Z2guYm9yaW5nYXZhdGFycy5kZXYvYXBpL2F2YXRhcj92YXJpYW50PWJlYW0mbmFtZT12c2QmY29sb3JzPUVGRUFFNixFRUFGM0EsMDMwRTBGLEVGOUZCQ2csNjVDM0M4JnNxdWFyZSIsInN1YiI6IjUzMzkiLCJyb2xlIjoiY3JlYXRvciIsImlhdCI6MTc0OTcwNzk0MH0.aC-n2NHT-usv7uXCtPwJZjPgMBkfQrtXDKX9g0yj1f0",
    "Venu": "speedoughSession=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJ2YXNkd29yayIsImVtYWlsIjoidmFzZHdvcmsyMDI1QGdtYWlsLmNvbSIsImVtYWlsVmVyaWZpZWQiOm51bGwsImlzX2FjdGl2ZSI6dHJ1ZSwiaXNfc3VwZXJ1c2VyIjpmYWxzZSwiaW1hZ2UiOiJodHRwczovL3NwZWVkb3VnaC5ib3JpbmdhdmF0YXJzLmRldi9hcGkvYXZhdGFyP3ZhcmlhbnQ9YmVhbSZuYW1lPXZhc2R3b3JrJmNvbG9ycz1FRkVBRTYsRUVBRjNBLDAzMEUwRixFRjlGQkNnLDY1QzNDOCZzcXVhcmUiLCJyb2xlIjoiY3JlYXRvciIsImNyZWF0b3JfaWQiOjUxODksImNyZWF0ZWRfYXQiOiIyMDI1LTA2LTEyVDAxOjU2OjQ2LjI5MFoiLCJ1cGRhdGVkX2F0IjoiMjAyNS0wNi0xMlQwMTo1NzoxMi42NzhaIiwiaWQiOiI1MzM4IiwiZmF2b3JpdGVfcmV0YWlsZXJzIjpbXX0sIm5hbWUiOiJ2YXNkd29yayIsImVtYWlsIjoidmFzZHdvcmsyMDI1QGdtYWlsLmNvbSIsInBpY3R1cmUiOiJodHRwczovL3NwZWVkb3VnaC5ib3JpbmdhdmF0YXJzLmRldi9hcGkvYXZhdGFyP3ZhcmlhbnQ9YmVhbSZuYW1lPXZhc2R3b3JrJmNvbG9ycz1FRkVBRTYsRUVBRjNBLDAzMEUwRixFRjlGQkNnLDY1QzNDOCZzcXVhcmUiLCJzdWIiOiI1MzM4Iiwicm9sZSI6ImNyZWF0b3IiLCJpYXQiOjE3NDk3MDczMzV9.J4DA5NwSpDHqu2Tp8IEQOC4Ws2MX8mr42dT3Lkv0UM4",
    "L-Harsha": "speedoughSession=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJsc2Qgd29yayIsImVtYWlsIjoibHNkd29yazIwMjVAZ21haWwuY29tIiwiZW1haWxWZXJpZmllZCI6bnVsbCwiaXNfYWN0aXZlIjp0cnVlLCJpc19zdXBlcnVzZXIiOmZhbHNlLCJpbWFnZSI6Imh0dHBzOi8vc3BlZWRvdWdoLmJvcmluZ2F2YXRhcnMuZGV2L2FwaS9hdmF0YXI_dmFyaWFudD1iZWFtJm5hbWU9bHNkIHdvcmsmY29sb3JzPUVGRUFFNixFRUFGM0EsMDMwRTBGLEVGOUZCQ2csNjVDM0M4JnNxdWFyZSIsInJvbGUiOiJjcmVhdG9yIiwiY3JlYXRvcl9pZCI6NTE4NywiY3JlYXRlZF9hdCI6IjIwMjUtMDYtMTJUMDE6NDk6MTIuMTcyWiIsInVwZGF0ZWRfYXQiOiIyMDI1LTA2LTEyVDAxOjUwOjMyLjI5NloiLCJpZCI6IjUzMzYiLCJmYXZvcml0ZV9yZXRhaWxlcnMiOltdfSwibmFtZSI6ImxzZCB3b3JrIiwiZW1haWwiOiJsc2R3b3JrMjAyNUBnbWFpbC5jb20iLCJwaWN0dXJlIjoiaHR0cHM6Ly9zcGVlZG91Z2guYm9yaW5nYXZhdGFycy5kZXYvYXBpL2F2YXRhcj92YXJpYW50PWJlYW0mbmFtZT1sc2Qgd29yayZjb2xvcnM9RUZFQUU2LEVFQUYzQSwwMzBFMEYsRUY5RkJDZyw2NUMzQzgmc3F1YXJlIiwic3ViIjoiNTMzNiIsInJvbGUiOiJjcmVhdG9yIiwiaWF0IjoxNzQ5NzA3MTE1fQ.W02NYfeLIk_zL-lauI7WLbxxSLvc8rbHb7vfVHBpo7A",
    "R-Ragh": "speedoughSession=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJyc2QiLCJlbWFpbCI6InJzZHdvcmsyMDI1QGdtYWlsLmNvbSIsImVtYWlsVmVyaWZpZWQiOm51bGwsImlzX2FjdGl2ZSI6dHJ1ZSwiaXNfc3VwZXJ1c2VyIjpmYWxzZSwiaW1hZ2UiOiJodHRwczovL3NwZWVkb3VnaC5ib3JpbmdhdmF0YXJzLmRldi9hcGkvYXZhdGFyP3ZhcmlhbnQ9YmVhbSZuYW1lPXJzZCZjb2xvcnM9RUZFQUU2LEVFQUYzQSwwMzBFMEYsRUY5RkJDZyw2NUMzQzgmc3F1YXJlIiwicm9sZSI6ImNyZWF0b3IiLCJjcmVhdG9yX2lkIjo1NDU2LCJjcmVhdGVkX2F0IjoiMjAyNS0wNi0yNlQwNzoyMTowNi43OTNaIiwidXBkYXRlZF9hdCI6IjIwMjUtMDYtMjZUMDc6MjM6MjAuMDIzWiIsImlkIjoiNTYwOCIsImZhdm9yaXRlX3JldGFpbGVycyI6W119LCJuYW1lIjoicnNkIiwiZW1haWwiOiJyc2R3b3JrMjAyNUBnbWFpbC5jb20iLCJwaWN0dXJlIjoiaHR0cHM6Ly9zcGVlZG91Z2guYm9yaW5nYXZhdGFycy5kZXYvYXBpL2F2YXRhcj92YXJpYW50PWJlYW0mbmFtZT1yc2QmY29sb3JzPUVGRUFFNixFRUFGM0EsMDMwRTBGLEVGOUZCQ2csNjVDM0M4JnNxdWFyZSIsInN1YiI6IjU2MDgiLCJyb2xlIjoiY3JlYXRvciIsImlhdCI6MTc1MDk5MDU2Nn0.h70kCVsqAWTq8_A5YbSQhfsZNB2on5cRSz_sVRgLfiA",
    "R-Vaishnav": "speedoughSession=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJyb3NkIiwiZW1haWwiOiJyb3Nkd29yazIwMjVAZ21haWwuY29tIiwiZW1haWxWZXJpZmllZCI6bnVsbCwiaXNfYWN0aXZlIjp0cnVlLCJpc19zdXBlcnVzZXIiOmZhbHNlLCJpbWFnZSI6Imh0dHBzOi8vc3BlZWRvdWdoLmJvcmluZ2F2YXRhcnMuZGV2L2FwaS9hdmF0YXI_dmFyaWFudD1iZWFtJm5hbWU9cm9zZCZjb2xvcnM9RUZFQUU2LEVFQUYzQSwwMzBFMEYsRUY5RkJDZyw2NUMzQzgmc3F1YXJlIiwicm9sZSI6ImNyZWF0b3IiLCJjcmVhdG9yX2lkIjo1NDU3LCJjcmVhdGVkX2F0IjoiMjAyNS0wNi0yNlQwNzozMDoxNC44NzFaIiwidXBkYXRlZF9hdCI6IjIwMjUtMDYtMjZUMDc6MzA6NDYuMzk5WiIsImlkIjoiNTYwOSIsImZhdm9yaXRlX3JldGFpbGVycyI6W119LCJuYW1lIjoicm9zZCIsImVtYWlsIjoicm9zZHdvcmsyMDI1QGdtYWlsLmNvbSIsInBpY3R1cmUiOiJodHRwczovL3NwZWVkb3VnaC5ib3JpbmdhdmF0YXJzLmRldi9hcGkvYXZhdGFyP3ZhcmlhbnQ9YmVhbSZuYW1lPXJvc2QmY29sb3JzPUVGRUFFNixFRUFGM0EsMDMwRTBGLEVGOUZCQ2csNjVDM0M4JnNxdWFyZSIsInN1YiI6IjU2MDkiLCJyb2xlIjoiY3JlYXRvciIsImlhdCI6MTc1MDk5MDc1Mn0.dCCKod7QdtUR1Kp-W_PBbGbV-mARpWNKUmCMqoi5yrU",
    "Darksurf": "speedoughSession=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJEYXJrc3VyZiIsImVtYWlsIjoiZGFya3N1cmYwMDdAZ21haWwuY29tIiwiZW1haWxWZXJpZmllZCI6bnVsbCwiaXNfYWN0aXZlIjp0cnVlLCJpc19zdXBlcnVzZXIiOmZhbHNlLCJpbWFnZSI6Imh0dHBzOi8vZW5jcnlwdGVkLXRibjAuZ3N0YXRpYy5jb20vaW1hZ2VzP3E9dGJuOkFOZDlHY1RMeUE5OWdGZGVUaWVYSTdZU3pkVFJKdnFpRkNubWduM0tfYVZkOTh3UnFyYWoyQkZYUzJESW54Y3Ymcz0xMCIsInJvbGUiOiJjcmVhdG9yIiwiY3JlYXRvcl9pZCI6MzQ0MiwiY3JlYXRlZF9hdCI6IjIwMjUtMDEtMDVUMDA6MTc6MzUuMzU3WiIsInVwZGF0ZWRfYXQiOiIyMDI1LTAxLTI5VDE1OjA5OjQ2LjI3MVoiLCJpZCI6IjM1MjciLCJmYXZvcml0ZV9yZXRhaWxlcnMiOlsibm9yZHN0cm9tLmNvbSIsImh1ZHNvbmplYW5zLmNvbSIsImh1bHUuY29tIiwiYmFuYW5hcmVwdWJsaWNmYWN0b3J5LmdhcGZhY3RvcnkuY29tIiwiYWxscG9zdGVycy5jb20iLCJ0aGVvcnkuY29tIiwiYmVhdXR5cGx1c3NhbG9uLmNvbSIsImJ1Y2tsZS5jb20iLCJ6ZW5uaW9wdGljYWwuY29tIiwidGVjb3Zhcy5jb20iLCJibGFpci5jb20iLCJjYXRoZXJpbmVzLmNvbSIsInNwb3J0c3VubGltaXRlZGluYy5jb20iLCJsdW1lbnMuY29tIl19LCJuYW1lIjoiRGFya3N1cmYiLCJlbWFpbCI6ImRhcmtzdXJmMDA3QGdtYWlsLmNvbSIsInBpY3R1cmUiOiJodHRwczovL2VuY3J5cHRlZC10Ym4wLmdzdGF0aWMuY29tL2ltYWdlcz9xPXRibjpBTmQ5R2NUTHlBOTlnRmRlVGllWEk3WVN6ZFRSSnZxaUZDbm1nbjNLX2FWZDk4d1JxcmFqMkJGWFMyRElueGN2JnM9MTAiLCJzdWIiOiIzNTI3Iiwicm9sZSI6ImNyZWF0b3IiLCJpYXQiOjE3NDc1MDM2NTB9.HS8yvKkn2dnGyTO06DXEv5J5w_dtCJeuV9v-JRwJZdE",
    "Amrutha": "speedoughSession=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJhbXNkIiwiZW1haWwiOiJhbXNkd29yazIwMjVAZ21haWwuY29tIiwiZW1haWxWZXJpZmllZCI6bnVsbCwiaXNfYWN0aXZlIjp0cnVlLCJpc19zdXBlcnVzZXIiOmZhbHNlLCJpbWFnZSI6Imh0dHBzOi8vc3BlZWRvdWdoLmJvcmluZ2F2YXRhcnMuZGV2L2FwaS9hdmF0YXI_dmFyaWFudD1iZWFtJm5hbWU9YW1zZCZjb2xvcnM9RUZFQUU2LEVFQUYzQSwwMzBFMEYsRUY5RkJDZyw2NUMzQzgmc3F1YXJlIiwicm9sZSI6ImNyZWF0b3IiLCJjcmVhdG9yX2lkIjo1NjIwLCJjcmVhdGVkX2F0IjoiMjAyNS0wNy0wNVQxNjoxNzozMS45NzJaIiwidXBkYXRlZF9hdCI6IjIwMjUtMDctMDVUMTY6MTg6MTAuODczWiIsImlkIjoiNTc3NiIsImZhdm9yaXRlX3JldGFpbGVycyI6W119LCJuYW1lIjoiYW1zZCIsImVtYWlsIjoiYW1zZHdvcmsyMDI1QGdtYWlsLmNvbSIsInBpY3R1cmUiOiJodHRwczovL3NwZWVkb3VnaC5ib3JpbmdhdmF0YXJzLmRldi9hcGkvYXZhdGFyP3ZhcmlhbnQ9YmVhbSZuYW1lPWFtc2QmY29sb3JzPUVGRUFFNixFRUFGM0EsMDMwRTBGLEVGOUZCQ2csNjVDM0M4JnNxdWFyZSIsInN1YiI6IjU3NzYiLCJyb2xlIjoiY3JlYXRvciIsImlhdCI6MTc1MTczMjI5Nn0.MhNbwGAnFcc_jNMiK3MqHPBM5VhD0yMsWhY-lOyQBXw",
    "Prarthana": "speedoughSession=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJwcnNkIiwiZW1haWwiOiJwcnNkd29yazIwMjVAZ21haWwuY29tIiwiZW1haWxWZXJpZmllZCI6bnVsbCwiaXNfYWN0aXZlIjp0cnVlLCJpc19zdXBlcnVzZXIiOmZhbHNlLCJpbWFnZSI6Imh0dHBzOi8vc3BlZWRvdWdoLmJvcmluZ2F2YXRhcnMuZGV2L2FwaS9hdmF0YXI_dmFyaWFudD1iZWFtJm5hbWU9cHJzZCZjb2xvcnM9RUZFQUU2LEVFQUYzQSwwMzBFMEYsRUY5RkJDZyw2NUMzQzgmc3F1YXJlIiwicm9sZSI6ImNyZWF0b3IiLCJjcmVhdG9yX2lkIjo1NjIxLCJjcmVhdGVkX2F0IjoiMjAyNS0wNy0wNVQxNjoyMDo1MS43MzNaIiwidXBkYXRlZF9hdCI6IjIwMjUtMDctMDVUMTY6MjE6NDMuMjQzWiIsImlkIjoiNTc3NyIsImZhdm9yaXRlX3JldGFpbGVycyI6W119LCJuYW1lIjoicHJzZCIsImVtYWlsIjoicHJzZHdvcmsyMDI1QGdtYWlsLmNvbSIsInBpY3R1cmUiOiJodHRwczovL3NwZWVkb3VnaC5ib3JpbmdhdmF0YXJzLmRldi9hcGkvYXZhdGFyP3ZhcmlhbnQ9YmVhbSZuYW1lPXByc2QmY29sb3JzPUVGRUFFNixFRUFGM0EsMDMwRTBGLEVGOUZCQ2csNjVDM0M4JnNxdWFyZSIsInN1YiI6IjU3NzciLCJyb2xlIjoiY3JlYXRvciIsImlhdCI6MTc1MTczMjUxNH0.1aAmD6KBlQ00z4htNZcNIEuAWM8Is3faQspiGOZ-iv4",
    "Kavya": "speedoughSession=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJzeXNkIiwiZW1haWwiOiJzeXNkd29yazIwMjVAZ21haWwuY29tIiwiZW1haWxWZXJpZmllZCI6bnVsbCwiaXNfYWN0aXZlIjp0cnVlLCJpc19zdXBlcnVzZXIiOmZhbHNlLCJpbWFnZSI6Imh0dHBzOi8vc3BlZWRvdWdoLmJvcmluZ2F2YXRhcnMuZGV2L2FwaS9hdmF0YXI_dmFyaWFudD1iZWFtJm5hbWU9c3lzZCZjb2xvcnM9RUZFQUU2LEVFQUYzQSwwMzBFMEYsRUY5RkJDZyw2NUMzQzgmc3F1YXJlIiwicm9sZSI6ImNyZWF0b3IiLCJjcmVhdG9yX2lkIjo1NjI0LCJjcmVhdGVkX2F0IjoiMjAyNS0wNy0wNVQxNjozMjo0OS44NTNaIiwidXBkYXRlZF9hdCI6IjIwMjUtMDctMDVUMTY6MzM6NTAuMzIwWiIsImlkIjoiNTc4MCIsImZhdm9yaXRlX3JldGFpbGVycyI6W119LCJuYW1lIjoic3lzZCIsImVtYWlsIjoic3lzZHdvcmsyMDI1QGdtYWlsLmNvbSIsInBpY3R1cmUiOiJodHRwczovL3NwZWVkb3VnaC5ib3JpbmdhdmF0YXJzLmRldi9hcGkvYXZhdGFyP3ZhcmlhbnQ9YmVhbSZuYW1lPXN5c2QmY29sb3JzPUVGRUFFNixFRUFGM0EsMDMwRTBGLEVGOUZCQ2csNjVDM0M4JnNxdWFyZSIsInN1YiI6IjU3ODAiLCJyb2xlIjoiY3JlYXRvciIsImlhdCI6MTc1MTczMzI1M30.yHWM-KDDodhRXi9gkk8ovYRO2qo_vgaGqhW8Onhs9PQ",
    "Abhishek": "speedoughSession=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJhYnNkIiwiZW1haWwiOiJhYnNkd29yazIwMjVAZ21haWwuY29tIiwiZW1haWxWZXJpZmllZCI6bnVsbCwiaXNfYWN0aXZlIjp0cnVlLCJpc19zdXBlcnVzZXIiOmZhbHNlLCJpbWFnZSI6Imh0dHBzOi8vc3BlZWRvdWdoLmJvcmluZ2F2YXRhcnMuZGV2L2FwaS9hdmF0YXI_dmFyaWFudD1iZWFtJm5hbWU9YWJzZCZjb2xvcnM9RUZFQUU2LEVFQUYzQSwwMzBFMEYsRUY5RkJDZyw2NUMzQzgmc3F1YXJlIiwicm9sZSI6ImNyZWF0b3IiLCJjcmVhdG9yX2lkIjo1NjIyLCJjcmVhdGVkX2F0IjoiMjAyNS0wNy0wNVQxNjoyNjozOC42MDJaIiwidXBkYXRlZF9hdCI6IjIwMjUtMDctMDVUMTY6Mjc6MTIuNTc1WiIsImlkIjoiNTc3OCIsImZhdm9yaXRlX3JldGFpbGVycyI6W119LCJuYW1lIjoiYWJzZCIsImVtYWlsIjoiYWJzZHdvcmsyMDI1QGdtYWlsLmNvbSIsInBpY3R1cmUiOiJodHRwczovL3NwZWVkb3VnaC5ib3JpbmdhdmF0YXJzLmRldi9hcGkvYXZhdGFyP3ZhcmlhbnQ9YmVhbSZuYW1lPWFic2QmY29sb3JzPUVGRUFFNixFRUFGM0EsMDMwRTBGLEVGOUZCQ2csNjVDM0M4JnNxdWFyZSIsInN1YiI6IjU3NzgiLCJyb2xlIjoiY3JlYXRvciIsImlhdCI6MTc1MTczMjgzOX0.CKECRy-SZ_exxbbfmo2Do64Exq7ye4TqaS59zwZ9qhw",
    "Sudeep": "speedoughSession=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJzdXNkIiwiZW1haWwiOiJzdXNkd29yazIwMjVAZ21haWwuY29tIiwiZW1haWxWZXJpZmllZCI6bnVsbCwiaXNfYWN0aXZlIjp0cnVlLCJpc19zdXBlcnVzZXIiOmZhbHNlLCJpbWFnZSI6Imh0dHBzOi8vc3BlZWRvdWdoLmJvcmluZ2F2YXRhcnMuZGV2L2FwaS9hdmF0YXI_dmFyaWFudD1iZWFtJm5hbWU9c3VzZCZjb2xvcnM9RUZFQUU2LEVFQUYzQSwwMzBFMEYsRUY5RkJDZyw2NUMzQzgmc3F1YXJlIiwicm9sZSI6ImNyZWF0b3IiLCJjcmVhdG9yX2lkIjo1NjIzLCJjcmVhdGVkX2F0IjoiMjAyNS0wNy0wNVQxNjozMjoxNS42ODRaIiwidXBkYXRlZF9hdCI6IjIwMjUtMDctMDVUMTY6MzM6NTguMTMyWiIsImlkIjoiNTc3OSIsImZhdm9yaXRlX3JldGFpbGVycyI6W119LCJuYW1lIjoic3VzZCIsImVtYWlsIjoic3VzZHdvcmsyMDI1QGdtYWlsLmNvbSIsInBpY3R1cmUiOiJodHRwczovL3NwZWVkb3VnaC5ib3JpbmdhdmF0YXJzLmRldi9hcGkvYXZhdGFyP3ZhcmlhbnQ9YmVhbSZuYW1lPXN1c2QmY29sb3JzPUVGRUFFNixFRUFGM0EsMDMwRTBGLEVGOUZCQ2csNjVDM0M4JnNxdWFyZSIsInN1YiI6IjU3NzkiLCJyb2xlIjoiY3JlYXRvciIsImlhdCI6MTc1MTczMzI0NX0.VRN1Gpo8_AsBQBdiF-bnNNrP92y6j_0BYjcUrbtaH0Y",
    "Harshitha": "speedoughSession=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJoc2QiLCJlbWFpbCI6IjFoc2R3b3JrMjAyNUBnbWFpbC5jb20iLCJlbWFpbFZlcmlmaWVkIjpudWxsLCJpc19hY3RpdmUiOnRydWUsImlzX3N1cGVydXNlciI6ZmFsc2UsImltYWdlIjoiaHR0cHM6Ly9zcGVlZG91Z2guYm9yaW5nYXZhdGFycy5kZXYvYXBpL2F2YXRhcj92YXJpYW50PWJlYW0mbmFtZT1oc2QmY29sb3JzPUVGRUFFNixFRUFGM0EsMDMwRTBGLEVGOUZCQ2csNjVDM0M4JnNxdWFyZSIsInJvbGUiOiJjcmVhdG9yIiwiY3JlYXRvcl9pZCI6NTY5MSwiY3JlYXRlZF9hdCI6IjIwMjUtMDctMDlUMTQ6NDA6MTMuNDkxWiIsInVwZGF0ZWRfYXQiOiIyMDI1LTA3LTA5VDE0OjQwOjM4LjgxMVoiLCJpZCI6IjU4NDciLCJmYXZvcml0ZV9yZXRhaWxlcnMiOltdfSwibmFtZSI6ImhzZCIsImVtYWlsIjoiMWhzZHdvcmsyMDI1QGdtYWlsLmNvbSIsInBpY3R1cmUiOiJodHRwczovL3NwZWVkb3VnaC5ib3JpbmdhdmF0YXJzLmRldi9hcGkvYXZhdGFyP3ZhcmlhbnQ9YmVhbSZuYW1lPWhzZCZjb2xvcnM9RUZFQUU2LEVFQUYzQSwwMzBFMEYsRUY5RkJDZyw2NUMzQzgmc3F1YXJlIiwic3ViIjoiNTg0NyIsInJvbGUiOiJjcmVhdG9yIiwiaWF0IjoxNzUyMTYzOTkyfQ.g3vSv2qb5xR7lOZItvu5gnjbj-I1AYcJpRSi-MEukJY",
    "Jyothika": "speedoughSession=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJqeXNkIiwiZW1haWwiOiJqeXNkd29yazIwMjVAZ21haWwuY29tIiwiZW1haWxWZXJpZmllZCI6bnVsbCwiaXNfYWN0aXZlIjp0cnVlLCJpc19zdXBlcnVzZXIiOmZhbHNlLCJpbWFnZSI6Imh0dHBzOi8vc3BlZWRvdWdoLmJvcmluZ2F2YXRhcnMuZGV2L2FwaS9hdmF0YXI_dmFyaWFudD1iZWFtJm5hbWU9anlzZCZjb2xvcnM9RUZFQUU2LEVFQUYzQSwwMzBFMEYsRUY5RkJDZyw2NUMzQzgmc3F1YXJlIiwicm9sZSI6ImNyZWF0b3IiLCJjcmVhdG9yX2lkIjo1NjkyLCJjcmVhdGVkX2F0IjoiMjAyNS0wNy0wOVQxNDo0NToyMi4wNzVaIiwidXBkYXRlZF9hdCI6IjIwMjUtMDctMDlUMTQ6NDU6NDkuMzc4WiIsImlkIjoiNTg0OCIsImZhdm9yaXRlX3JldGFpbGVycyI6W119LCJuYW1lIjoianlzZCIsImVtYWlsIjoianlzZHdvcmsyMDI1QGdtYWlsLmNvbSIsInBpY3R1cmUiOiJodHRwczovL3NwZWVkb3VnaC5ib3JpbmdhdmF0YXJzLmRldi9hcGkvYXZhdGFyP3ZhcmlhbnQ9YmVhbSZuYW1lPWp5c2QmY29sb3JzPUVGRUFFNixFRUFGM0EsMDMwRTBGLEVGOUZCQ2csNjVDM0M4JnNxdWFyZSIsInN1YiI6IjU4NDgiLCJyb2xlIjoiY3JlYXRvciIsImlhdCI6MTc1MjE2NDQ4Mn0.ThnhU1eNJAJrq0LaLs0RN8nurGZ94FBVfg2NU7ahgj8",
    "Bhavana": "speedoughSession=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJic2QiLCJlbWFpbCI6ImJzZHdvcmsyMDI1QGdtYWlsLmNvbSIsImVtYWlsVmVyaWZpZWQiOm51bGwsImlzX2FjdGl2ZSI6dHJ1ZSwiaXNfc3VwZXJ1c2VyIjpmYWxzZSwiaW1hZ2UiOiJodHRwczovL3NwZWVkb3VnaC5ib3JpbmdhdmF0YXJzLmRldi9hcGkvYXZhdGFyP3ZhcmlhbnQ9YmVhbSZuYW1lPWJzZCZjb2xvcnM9RUZFQUU2LEVFQUYzQSwwMzBFMEYsRUY5RkJDZyw2NUMzQzgmc3F1YXJlIiwicm9sZSI6ImNyZWF0b3IiLCJjcmVhdG9yX2lkIjo1Njk0LCJjcmVhdGVkX2F0IjoiMjAyNS0wNy0wOVQxNDo1MTo1Ni41OTZaIiwidXBkYXRlZF9hdCI6IjIwMjUtMDctMDlUMTQ6NTI6MTguNDcwWiIsImlkIjoiNTg1MCIsImZhdm9yaXRlX3JldGFpbGVycyI6W119LCJuYW1lIjoiYnNkIiwiZW1haWwiOiJic2R3b3JrMjAyNUBnbWFpbC5jb20iLCJwaWN0dXJlIjoiaHR0cHM6Ly9zcGVlZG91Z2guYm9yaW5nYXZhdGFycy5kZXYvYXBpL2F2YXRhcj92YXJpYW50PWJlYW0mbmFtZT1ic2QmY29sb3JzPUVGRUFFNixFRUFGM0EsMDMwRTBGLEVGOUZCQ2csNjVDM0M4JnNxdWFyZSIsInN1YiI6IjU4NTAiLCJyb2xlIjoiY3JlYXRvciIsImlhdCI6MTc1MjE2NDYxMH0.2Wf5poF7erOxN36RJEUvJcgIeVYyiH3dKS_wxdHno6o",
    "Diksha": "speedoughSession=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJkc2QiLCJlbWFpbCI6ImRzZHdvcmsyMDI1QGdtYWlsLmNvbSIsImVtYWlsVmVyaWZpZWQiOm51bGwsImlzX2FjdGl2ZSI6dHJ1ZSwiaXNfc3VwZXJ1c2VyIjpmYWxzZSwiaW1hZ2UiOiJodHRwczovL3NwZWVkb3VnaC5ib3JpbmdhdmF0YXJzLmRldi9hcGkvYXZhdGFyP3ZhcmlhbnQ9YmVhbSZuYW1lPWRzZCZjb2xvcnM9RUZFQUU2LEVFQUYzQSwwMzBFMEYsRUY5RkJDZyw2NUMzQzgmc3F1YXJlIiwicm9sZSI6ImNyZWF0b3IiLCJjcmVhdG9yX2lkIjo1Njk1LCJjcmVhdGVkX2F0IjoiMjAyNS0wNy0wOVQxNTowMDoyNy4yMTBaIiwidXBkYXRlZF9hdCI6IjIwMjUtMDctMDlUMTU6MDA6NTEuMDg5WiIsImlkIjoiNTg1MSIsImZhdm9yaXRlX3JldGFpbGVycyI6W119LCJuYW1lIjoiZHNkIiwiZW1haWwiOiJkc2R3b3JrMjAyNUBnbWFpbC5jb20iLCJwaWN0dXJlIjoiaHR0cHM6Ly9zcGVlZG91Z2guYm9yaW5nYXZhdGFycy5kZXYvYXBpL2F2YXRhcj92YXJpYW50PWJlYW0mbmFtZT1kc2QmY29sb3JzPUVGRUFFNixFRUFGM0EsMDMwRTBGLEVGOUZCQ2csNjVDM0M4JnNxdWFyZSIsInN1YiI6IjU4NTEiLCJyb2xlIjoiY3JlYXRvciIsImlhdCI6MTc1MjE2NDc1N30.QppKXIBPrlSAl7s4mtj91w1HyDaB7BqXFg28Am7t2Ro",
    "Nagma": "speedoughSession=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJOYSBTRCIsImVtYWlsIjoibmFzZHdvcmsyMDI1QGdtYWlsLmNvbSIsImVtYWlsVmVyaWZpZWQiOm51bGwsImlzX2FjdGl2ZSI6dHJ1ZSwiaXNfc3VwZXJ1c2VyIjpmYWxzZSwiaW1hZ2UiOiJodHRwczovL3NwZWVkb3VnaC5ib3JpbmdhdmF0YXJzLmRldi9hcGkvYXZhdGFyP3ZhcmlhbnQ9YmVhbSZuYW1lPU5hIFNEJmNvbG9ycz1FRkVBRTYsRUVBRjNBLDAzMEUwRixFRjlGQkNnLDY1QzNDOCZzcXVhcmUiLCJyb2xlIjoiY3JlYXRvciIsImNyZWF0b3JfaWQiOjU3NDIsImNyZWF0ZWRfYXQiOiIyMDI1LTA3LTExVDE1OjQ2OjIzLjI1NloiLCJ1cGRhdGVkX2F0IjoiMjAyNS0wNy0xMVQxNTo0NzowNC4zNzhaIiwiaWQiOiI1OTAwIiwiZmF2b3JpdGVfcmV0YWlsZXJzIjpbXX0sIm5hbWUiOiJOYSBTRCIsImVtYWlsIjoibmFzZHdvcmsyMDI1QGdtYWlsLmNvbSIsInBpY3R1cmUiOiJodHRwczovL3NwZWVkb3VnaC5ib3JpbmdhdmF0YXJzLmRldi9hcGkvYXZhdGFyP3ZhcmlhbnQ9YmVhbSZuYW1lPU5hIFNEJmNvbG9ycz1FRkVBRTYsRUVBRjNBLDAzMEUwRixFRjlGQkNnLDY1QzNDOCZzcXVhcmUiLCJzdWIiOiI1OTAwIiwicm9sZSI6ImNyZWF0b3IiLCJpYXQiOjE3NTIyNDg4MzN9.eYmBBGEY7YlCpW88e1nzZcl7IbJGLunGAm4FcCc8Eqw",
    "Ayan": "speedoughSession=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJheXNkIiwiZW1haWwiOiJheXNkd29yazIwMjVAZ21haWwuY29tIiwiZW1haWxWZXJpZmllZCI6bnVsbCwiaXNfYWN0aXZlIjp0cnVlLCJpc19zdXBlcnVzZXIiOmZhbHNlLCJpbWFnZSI6Imh0dHBzOi8vc3BlZWRvdWdoLmJvcmluZ2F2YXRhcnMuZGV2L2FwaS9hdmF0YXI_dmFyaWFudD1iZWFtJm5hbWU9YXlzZCZjb2xvcnM9RUZFQUU2LEVFQUYzQSwwMzBFMEYsRUY5RkJDZyw2NUMzQzgmc3F1YXJlIiwicm9sZSI6ImNyZWF0b3IiLCJjcmVhdG9yX2lkIjo1NDU4LCJjcmVhdGVkX2F0IjoiMjAyNS0wNi0yNlQwNzo1MzoyNi44NDlaIiwidXBkYXRlZF9hdCI6IjIwMjUtMDYtMjZUMDc6NTQ6MDQuNzg0WiIsImlkIjoiNTYxMCIsImZhdm9yaXRlX3JldGFpbGVycyI6W119LCJuYW1lIjoiYXlzZCIsImVtYWlsIjoiYXlzZHdvcmsyMDI1QGdtYWlsLmNvbSIsInBpY3R1cmUiOiJodHRwczovL3NwZWVkb3VnaC5ib3JpbmdhdmF0YXJzLmRldi9hcGkvYXZhdGFyP3ZhcmlhbnQ9YmVhbSZuYW1lPWF5c2QmY29sb3JzPUVGRUFFNixFRUFGM0EsMDMwRTBGLEVGOUZCQ2csNjVDM0M4JnNxdWFyZSIsInN1YiI6IjU2MTAiLCJyb2xlIjoiY3JlYXRvciIsImlhdCI6MTc1MDk5MDkxN30.G-mbUzk6coovPOVUHYGFguFK7JKdLHrJsiZKyexZcYw",
}

url = "https://speedough.com/serp/earnings/yesterday"
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/1392772509774119003/ymEW8AmnIZ68-L93MOLrT-7uScilBDBgHmGV_0_V2SEgHvUWOdCl9xdETn9UsrLYlidV"

def cookie_string_to_dict(cookie_str):
    cookies = []
    for item in cookie_str.split(';'):
        name, value = item.strip().split('=', 1)
        cookies.append({
            'name': name,
            'value': value,
            'domain': 'speedough.com',
            'path': '/',
            'secure': True,
            'httpOnly': False
        })
    return cookies

def extract_stats_from_html(html):
    soup = BeautifulSoup(html, "html.parser")
    stat_divs = soup.select("div.stat")

    values = {}
    for div in stat_divs:
        title_el = div.select_one(".stat-title")
        value_el = div.select_one(".stat-value div")
        if title_el and value_el:
            title = title_el.get_text(strip=True)
            value = value_el.get_text(strip=True)
            values[title] = value
    return {
        "Page Loads": values.get("Page Loads", "N/A"),
        "Click 1": values.get("Click 1", "N/A"),
        "Click 2": values.get("Click 2", "N/A"),
        "CTR1": values.get("CTR1", "N/A"),
        "CTR2": values.get("CTR2", "N/A"),
        "Full CTR": values.get("Full CTR", "N/A"),
        "RPC": values.get("RPC", "N/A"),
        "Total Revenue": values.get("Total Revenue", "0.00"),
    }

def get_user_stats(name, cookie_string):
    if not cookie_string:
        return {
            "Page Loads": "N/A",
            "Click 1": "N/A",
            "Click 2": "N/A",
            "CTR1": "N/A",
            "CTR2": "N/A",
            "Full CTR": "N/A",
            "RPC": "N/A",
            "Total Revenue": "0.00",
        }

    options = Options()
    options.add_argument("--headless=new")
    options.add_argument("--disable-gpu")
    options.add_argument("--no-sandbox")
    driver = webdriver.Chrome(options=options)

    driver.get("https://speedough.com")
    time.sleep(1)

    cookies = cookie_string_to_dict(cookie_string)
    for cookie in cookies:
        driver.add_cookie(cookie)

    driver.get(url)
    time.sleep(2)

    stats = extract_stats_from_html(driver.page_source)
    driver.quit()
    return stats

def display_stats(name, stats):
    print(f"\n👤 {name}")
    print("-" * 30)
    print(f"Page Loads     : {stats['Page Loads']}")
    print(f"Click 1        : {stats['Click 1']}")
    print(f"Click 2        : {stats['Click 2']}")
    print(f"CTR1           : {stats['CTR1']}")
    print(f"CTR2           : {stats['CTR2']}")
    print(f"Full CTR       : {stats['Full CTR']}")
    print(f"RPC            : {stats['RPC']}")
    print(f"Total Revenue  : ${stats['Total Revenue']}")
    print("-" * 30)

def send_to_discord(message):
    try:
        response = requests.post(DISCORD_WEBHOOK_URL, json={"content": message})
        if response.status_code != 204:
            print(f"❌ Failed to send to Discord: {response.status_code} {response.text}")
    except Exception as e:
        print(f"❌ Error sending to Discord: {e}")

if __name__ == "__main__":
    print("🔄 Fetching Speedough Stats...\n")
    total_revenue = 0.0
    discord_message = "**📊 Speedough Daily Stats:**\n"

    for name in tqdm(user_cookie_strings.keys(), desc="Progress", unit="user"):
        try:
            stats = get_user_stats(name, user_cookie_strings[name])
            display_stats(name, stats)
            revenue = float(stats["Total Revenue"].replace('$', '').replace(',', '') or "0.00")
            total_revenue += revenue

            discord_message += (
                f"\n👤 **{name}**\n"
                f"Page Loads: {stats['Page Loads']}, "
                f"Click 1: {stats['Click 1']}, "
                f"Click 2: {stats['Click 2']}, "
                f"RPC: {stats['RPC']}, "
                f"Revenue: ${stats['Total Revenue']}\n"
            )
        except Exception as e:
            error_msg = f"❌ Failed to fetch stats for {name}: {e}"
            print(error_msg)
            discord_message += f"\n{error_msg}"

    summary = "\n📈 **Total Revenue (All Users)**: ${:.2f}".format(total_revenue)
    print(summary)
    discord_message += summary

    send_to_discord(discord_message)
