name: Speedough Bot

on:
  schedule:
    - cron: '45 18-23 * * *'  # Runs from 12:15 AM to 5:15 AM IST
    - cron: '45 0-6 * * *'    # Runs from 6:15 AM to 12:15 PM IST
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        run: python main.py
